# Generated by Django 3.0.5 on 2020-04-27 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low'), ('RELEASED', 'Released')], default='MODERATE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=35)),
                ('project_wiki', djrichtextfield.models.RichTextField()),
                ('project_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['project_date'],
            },
        ),
        migrations.CreateModel(
            name='Status_bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('TO_BE_DISCUSSED', 'To Be Discussed')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('ENHANCEMENT', 'Enhancement'), ('BUG', 'Bug'), ('UI/UX', 'Ui/Ux'), ('DUPLICATE', 'Duplicate')], default='BUG', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('display_picture', models.ImageField(height_field=83, upload_to='assignment/media/', width_field=89)),
                ('user_roles', models.CharField(max_length=30)),
                ('enrol_number', models.IntegerField()),
                ('branch_name', models.CharField(max_length=30)),
                ('current_year', models.PositiveSmallIntegerField()),
                ('degree_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_members', models.ManyToManyField(to='bugfeed.Users')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Users'),
        ),
        migrations.AddField(
            model_name='projects',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Priority'),
        ),
        migrations.CreateModel(
            name='Project_bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_heading', models.CharField(max_length=30)),
                ('bug_description', djrichtextfield.models.RichTextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('assigned_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Team')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Tags')),
                ('project_bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Projects')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Users')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Status_bugs')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.PositiveSmallIntegerField()),
                ('bug_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Project_bugs')),
                ('liked_by', models.ManyToManyField(to='bugfeed.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=500)),
                ('comment_time', models.DateTimeField()),
                ('bug_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Project_bugs')),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugfeed.Users')),
            ],
        ),
    ]
