# Generated by Django 3.0.5 on 2020-04-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0002_projects_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_roles',
        ),
        migrations.AddField(
            model_name='users',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project_bugs',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugfeed.Team'),
        ),
        migrations.RemoveField(
            model_name='project_bugs',
            name='category',
        ),
        migrations.AddField(
            model_name='project_bugs',
            name='category',
            field=models.ManyToManyField(to='bugfeed.Tags'),
        ),
        migrations.AlterField(
            model_name='project_bugs',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('TO_BE_DISCUSSED', 'To Be Discussed')], default='RESOLVED', max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='branch_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='users',
            name='display_picture',
            field=models.ImageField(null=True, upload_to='assignment/media/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='enrol_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Status_bugs',
        ),
    ]
