# Generated by Django 3.0.5 on 2020-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0003_auto_20200428_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='value',
            new_name='tag_value',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='priority',
        ),
        migrations.AddField(
            model_name='projects',
            name='priority_value',
            field=models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low'), ('RELEASED', 'Released')], default='MODERATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='degree_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
