# Generated by Django 3.0.5 on 2020-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.URLField(default=''),
        ),
    ]
