# Generated by Django 3.0.6 on 2020-07-14 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='project_bugs',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
