# Generated by Django 3.0.6 on 2020-06-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0002_users_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
