# Generated by Django 3.0.6 on 2020-07-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0004_auto_20200719_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_date',
            field=models.DateField(editable=False),
        ),
    ]
