# Generated by Django 3.0.5 on 2020-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0005_auto_20200502_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_bugs',
            name='other_text',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_value',
            field=models.CharField(choices=[('ENHANCEMENT', 'Enhancement'), ('BUG', 'Bug'), ('UI/UX', 'Ui/Ux'), ('DUPLICATE', 'Duplicate'), ('OTHERS', 'Others')], default='BUG', max_length=20),
        ),
    ]
