# Generated by Django 3.0.6 on 2020-07-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0005_auto_20200719_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_bugs',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('TO_BE_DISCUSSED', 'To Be Discussed')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_value',
            field=models.CharField(max_length=30),
        ),
    ]
