# Generated by Django 3.0.6 on 2020-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0006_auto_20200725_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_bugs',
            name='timestamp',
            field=models.DateField(editable=False),
        ),
    ]
