# Generated by Django 3.0.5 on 2020-05-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0006_auto_20200506_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_master',
            field=models.BooleanField(default=True),
        ),
    ]
