# Generated by Django 3.0.5 on 2020-05-23 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0007_auto_20200518_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='updated_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bugfeed.Users'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
