# Generated by Django 3.0.6 on 2020-07-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0008_auto_20200725_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_bugs',
            options={},
        ),
        migrations.RemoveField(
            model_name='project_bugs',
            name='timestamp',
        ),
    ]
