# Generated by Django 3.0.6 on 2020-06-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0009_auto_20200608_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='degree_name',
            field=models.CharField(max_length=80),
        ),
    ]
