# Generated by Django 3.0.6 on 2020-07-26 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugfeed', '0009_auto_20200725_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_bugs',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='project_bugs',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
